# Generated by Django 5.2.7 on 2025-10-28 23:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='end',
        ),
        migrations.RemoveField(
            model_name='provider',
            name='specialties',
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='specialty',
            field=models.ForeignKey(to='appointments.specialty', on_delete=django.db.models.deletion.PROTECT, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='appointments.provider'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='requested', max_length=10),
        ),
        migrations.AlterField(
            model_name='provider',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('provider', 'start', 'end')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['provider', 'start', 'end'], name='appointment_provide_f81b64_idx'),
        ),
        migrations.AddField(
            model_name='availability',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='appointments.provider'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['provider', 'start', 'end'], name='appointment_provide_e008cd_idx'),
        ),
    ]
