# Generated by Django 5.2.7 on 2025-12-02 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='provider',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='provider_photos/'),
        ),
    ]
