# Generated by Django 5.2.7 on 2025-12-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_provider_is_approved_provider_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
